config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  resources :users, only: [:show, :index, :edit, :update] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'bookmarks' => 'bookmarks#index', as: 'bookmarks'
    get 'groups' => 'groups#index', as: 'groups'
    get 'notifications' => 'notifications#index', as: 'notifications'
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end
  resources :categories, except: [:destroy] do
    resources :category_images, only: [:create]
    resources :groups, except: [:show, :index, :update]
    get 'join' => 'categories#join'
    delete 'leave' => 'categories#leave'
  end
  resources :groups, only: [:show, :update] do
    resources :messages, only: [:create]
    get 'join' => 'groups#join'
    get 'allow/:id' => 'groups#allow', as: 'allow'
    delete 'leave/:id' => 'groups#leave', as: 'leave'
  end
  resources :tags
  get 'search' => 'searches#search'
  get 'tags/:tag_id/posts' => 'posts#search', as: 'tag_post'
  delete 'notifications/destroy_all' => 'notifications#destroy_all', as: 'notification'
  post 'follow/:id' => 'relationships#create', as: 'follow'
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow'
  post 'category_images/:category_image_id/favorite' => 'favorites#create', as: 'favorites'
  delete 'category_images/:category_image_id/favorite' => 'favorites#destroy', as: 'favorite'
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages, dependent: :destroy
  belongs_to :category

  validates :name, presence: true, length: { in: 2..20, allow_blank: true }
  validates :introduction, presence: true, length: { in: 2..100, allow_blank: true }

  # グループメンバーか確かめる
  def group_member?(user)
    group_users.where(user_id: user.id, status: "join").exists?
  end

  def already_requested?(user)
    group_users.where(user_id: user.id).exists?
  end

  # メッセージが送信された時にメッセージ通知を保存
  def create_notification_message!(current_user, message_id)
    member_ids =
      GroupUser.select(:user_id).where(group_id: id).where.not(user_id: current_user.id).distinct
    member_ids.each do |memder_id|
      save_notification_message!(current_user, message_id, memder_id['user_id'])
    end
    save_notification_message!(current_user, message_id, user_ids) if member_ids.blank?
  end

  def save_notification_message!(current_user, message_id, visited_id)
    notification = current_user.active_notifications.new(
      group_id: id,
      message_id: message_id,
      visited_id: visited_id,
      action: 'message'
    )

    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update]
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_category_member, only: [:show, :edit]

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
    @category = Category.find(params[:category_id])
    unless @category.users.include?(current_user)
      redirect_to group_path(@category)
    end
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @category = Category.find(params[:category_id])
    @group.category_id = @category.id
    if @group.save
      @group.group_users.create(user: current_user, status: 1)
      redirect_to group_path(@group), notice: "グループを作成しました。"
    else
      render :new
    end
  end

  def show
    @members = GroupUser.where(group_id: @group.id, status: "join")
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def edit
  end

  def update
    if @group.save
      redirect_to group_path(@group)
    else
      render :edit
    end
  end

  def join
    @group = Group.find(params[:group_id])
    unless @group.users.include?(current_user)
      @group.users << current_user
      redirect_to group_path(@group)
    end
  end

  def allow
    group = Group.find(params[:group_id])
    user = User.find(params[:id])
    group_user = GroupUser.where(user_id: user.id, group_id: group.id)
    group_user.update(status: 1)
    redirect_back(fallback_location: root_path)
  end

  def leave
    group = Group.find(params[:group_id])
    user = User.find(params[:id])
    GroupUser.find_by(user_id: user.id, group_id: group.id).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to category_path(@group.category)
    end
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def ensure_category_member
    group = Group.find(params[:id])
    unless group.category.users.include?(current_user)
      flash[:notice] = "カテゴリー登録をしてください"
      redirect_to category_path(group.category)
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= render "layouts/errors", obj: @group %>
<%= form_with model:[category, group], local:true do |f| %>
  <div class="form-group">
    <%= f.label :グループ名%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :紹介文%>
    <%= f.text_area :introduction, rows: "15", class: "form-control" %>
  </div>
  <div class="form-group">
    <% if action_name == "new" %>
      <%= f.submit "作成", class: "form-control btn"  %>
    <% else %>
      <%= f.submit "更新", class: "form-control btn"  %>
    <% end %>
  </div>
<% end %>

app/views/groups/_index.html.erb
<% groups.each do |group| %>
  <tr onclick='window.location="<%= '../../groups/' + group.id.to_s %>"' role="link" class="pointer">
    <td>
      <% if action_name == "index" %>
        <span><%= group.category.name %></span><br>
      <% end %>
      <%= group.name %>
    </td>
    <td><%= group.introduction %></td>
  </tr>
<% end %>

app/views/groups/edit.html.erb
<div class="group container">
  <div class="col-md-8 offset-md-2">
    <%= render "groups/form", category: @category, group: @group %>
  </div>
  <table class="table">
    <tbody>
      <% @group.group_users.each do |user| %>
        <tr>
          <td><%= link_to user.user.name, user_path(user.user) %></td>
          <% if @group.group_member?(user.user)%>
            <td><%= user.status_i18n %></td>
            <td><%= link_to "退出させる", group_leave_path(group_id: @group, id: user.user), method: :delete, class: "btn leave-btn" %></td>
          <% else %>
            <td><%= user.status_i18n %></td>
            <td><%= link_to "許可する", group_allow_path(group_id: @group, id: user.user), class: "btn allow-btn" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/index.html.erb
<div class="group container">
  <div class="row">
    <div class="group-field col-md-10 offset-1">
      <h5>グループ一覧</h5>
      <table class="table">
        <tbody>
          <%= render "groups/index", groups: @groups %>
        </tbody>
      </table>
    </div>
  </div>
  <%= render "users/nav-icons", user: current_user %>
</div>

app/views/groups/new.html.erb
<div class="group container">
  <div class="col-md-8 offset-md-2">
    <%= render "groups/form", category: @category, group: @group %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="group container">
  <div class="row">
    <div class="col-md-5">
      <h3>
        <span>
          <%= link_to @group.category.name, category_path(@group.category) %> > 
        </span>
        <%= @group.name %>
      </h3>
      <p class="group-setting">
        <% if @group.owner_id == current_user.id %>
          <%= link_to "編集", edit_category_group_path(@group.id) %>
        <% end %>
      </p>
      <div class="group-text">
        <%= simple_format @group.introduction %>
      </div>
      <div>
        <% if @group.already_requested?(current_user)%>
        　<% if @group.group_member?(current_user)%>
          　<%= link_to "退出", group_leave_path(group_id: @group, id: current_user), method: :delete, class: "btn leave-btn" %>
          <% else %>
          　<%= link_to "申請を取り消す", group_leave_path(group_id: @group, id: current_user), method: :delete, class: "btn leave-btn" %>
        　<% end %>
        <% else %>
          <%= link_to "参加", group_join_path(@group.id), class: "btn group-in" %>
        <% end %>
      </div>
      <p>グループメンバー</p>
      <div class="member-field">
        <% @members.each do |member| %>
          <div class="box">
            <%= link_to user_path(member.user) do %>
              <%= attachment_image_tag member.user, :profile_image, fallback: "no-image.jpg", class: "profile_image" %>
              <p><%= link_to member.user.name, user_path(member.user), class: "text-dark" %></p>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-6 offset-md-1">
      <div class="messages container">
        <div id="message" class="overflow-auto">
            <div class="table">
              <%= render "messages/messages", messages: @messages %>
            </div>
        </div>
        <% if @group.group_member?(current_user)%>
          <div class="form-group">
            <%=form_with model:[@group, @message], remote:true do |f| %>
              <%= f.text_area :content, class: "form-control", rows: "5", cols: "50" %>
              <%= f.submit "送信", placeholder: "メッセージを入力してください", class: "form-control btn" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag "message.js" %>