config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  resources :users, only: [:show, :index, :edit, :update] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'bookmarks' => 'bookmarks#index', as: 'bookmarks'
    get 'groups' => 'groups#index', as: 'groups'
    get 'notifications' => 'notifications#index', as: 'notifications'
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end
  resources :categories, except: [:destroy] do
    resources :category_images, only: [:create]
    resources :groups, except: [:show, :index, :update]
    get 'join' => 'categories#join'
    delete 'leave' => 'categories#leave'
  end
  resources :groups, only: [:show, :update] do
    resources :messages, only: [:create]
    get 'join' => 'groups#join'
    get 'allow/:id' => 'groups#allow', as: 'allow'
    delete 'leave/:id' => 'groups#leave', as: 'leave'
  end
  resources :tags
  get 'search' => 'searches#search'
  get 'tags/:tag_id/posts' => 'posts#search', as: 'tag_post'
  delete 'notifications/destroy_all' => 'notifications#destroy_all', as: 'notification'
  post 'follow/:id' => 'relationships#create', as: 'follow'
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow'
  post 'category_images/:category_image_id/favorite' => 'favorites#create', as: 'favorites'
  delete 'category_images/:category_image_id/favorite' => 'favorites#destroy', as: 'favorite'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :follower, class_name: "Reletionship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Reletionship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :bookmarks, dependent: :destroy
  has_many :category_users
  has_many :category, through: :category_users
  has_many :category_images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :group_requests, dependent: :destroy
  has_many :messages
  has_many :active_notifications,
    class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications,
    class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  attachment :profile_image
  attachment :home_image

  validates :name, presence: true, uniqueness: true, length: { in: 2..20, allow_blank: true }
  validates :profile, length: { maximum: 500 }

  # フォローをする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # フォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローをされているか確かめる
  def following?(user)
    following_user.include?(user)
  end

  # フォローされた時にフォロー通知を保存する
  def create_notification_follow!(current_user)
    temp = Notification.where([
      "visiter_id = ? and visited_id = ? and action = ? ",
      current_user.id, id, 'follow',
    ])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
  
  def already_requested?(group)
    self.group_requests.exists?(group_id: group.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index]
  before_action :ensure_correct_user, only: [:edit]

  def show
    @posts = @user.posts.page(params[:page]).per(12)
  end

  def index
    @users = User.page(params[:page]).per(15)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile, :profile_image, :home_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to edit_user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<% users.each do |user| %>
  <tr>
    <td>
      <%= attachment_image_tag user, :profile_image, fallback: "no-image.jpg", class: "profile-image-sm" %>
    </td>
    <td>
      <p><%= link_to user.name, user_path(user), class: "text-dark" %></p>
      <p id ="text-hidden-2"><%= user.profile %></p>
    </td>
    <td id="follow-btn_<%= user.id %>" class="follow-btn">
      <%= render "relationships/follow-btn", user: user %>
    </td>
  </tr>
<% end %>

app/views/users/_nav-icons.html.erb
<% if @user == current_user %>
    <div class="nav-icons">
      <%= link_to user_followings_path(user.id), class: "nav-icon" do %>
        <i class="far fa-user"></i>
        <p>Following</p>
      <% end %>
      <%= link_to user_followers_path(user.id), class: "nav-icon" do %>
        <i class="fas fa-user"></i>
        <p>Follower</p>
      <% end %>
      <%= link_to user_bookmarks_path(user.id), class: "nav-icon" do %>
        <i class="far fa-bookmark"></i>
        <p>Bookmark</p>
      <% end %>
      <%= link_to user_groups_path(user.id), class: "nav-icon" do %>
        <i class="fas fa-users"></i>
        <p>Groups</p>
      <% end %>
      <%= link_to user_notifications_path(user.id), class: "nav-icon" do %>
        <% if unchecked_notifications.any? %>
          <i class="far fa-lightbulb" style="color: gold;"></i>
        <% else %>
          <i class="far fa-lightbulb"></i>
        <% end %>
        <p>Notice</p>
      <% end %>
      <%= link_to edit_user_path(user), class: "nav-icon" do %>
        <i class="fas fa-cogs"></i>
        <p>Setting</p>
      <% end %>
    </div>
  <% else %>
    <div class="nav-icons">
      <%= link_to user_followings_path(user.id), class: "nav-icon" do %>
        <i class="far fa-user"></i>
        <p>Following</p>
      <% end %>
      <%= link_to user_followers_path(user.id), class: "nav-icon" do %>
        <i class="fas fa-user"></i>
        <p>Follower</p>
      <% end %>
      <%= link_to user_groups_path(user.id), class: "nav-icon" do %>
        <i class="fas fa-users"></i>
        <p>Groups</p>
      <% end %>
    </div>
  <% end %>

app/views/users/edit.html.erb
<div class="users container">
  <div class="col-md-8 offset-md-2">
    <%= render "layouts/errors", obj: @user %>
    <%= form_with model:@user, local:true do |f| %>
      <div class="user-setting form-group">
        <%= f.label :名前 %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="user-setting form-group">
        <%= f.label :プロフィール %>
        <%= f.text_area :profile, class: "form-control" %>
      </div>
      <div class="user-setting form-group item-image">
        <%= f.label :プロフィール画像 %>
        <%= f.attachment_field :profile_image, class: "form-control" %>
      </div>
      <div class="user-setting form-group">
        <%= f.label :背景画像 %>
        <%= f.attachment_field :home_image, class: "form-control" %>
      </div>
      <div class="user-setting form-group">
        <%= f.submit "更新" %>
      </div>
    <% end %>
  </div>
  <%= render "users/nav-icons", user: @user %>
</div>

app/views/users/index.html.erb
<div class="users container">
  <div class="row">
    <div class="col-md-6">
      <table class="table">
        <tbody>
          <%= render "users/index", users: @users %>
        </tbody>
      </table>
      <%= paginate @users %>
    </div>
    <div class="col-md-6">
      <div class="search-field">
        <% if user_signed_in? %>
        　<%= form_tag(search_path, method: :get) do %>
        　　<%= text_field_tag (:word), '', placeholder: "user検索" %>
        　　<%= hidden_field_tag 'range', 'user' %>
        　　<%= button_tag type: 'submit', class: 'btn btn-default' do %>
              <i class="fas fa-search"></i>
        　　<% end %>
        　<% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main-container">
  <%= attachment_image_tag @user, :home_image, fallback: "white.png", class: "main-visual image" %>
  <div class="main-visual"></div>
  <div class="info">
    <div class="profile-img">
      <%= attachment_image_tag @user, :profile_image, fallback: "no-image.jpg", class: "profile-image" %>
      <% if @user != current_user %>
        <div id="follow-btn_<%= @user.id %>" class="follow-btn">
          <%= render "relationships/follow-btn", user: @user %>
        </div>
      <% end %>
    </div>
    <div class="profile-text">
      <p>
        <span><%= @user.name %>ページ</span><br>
        <%= simple_format @user.profile %>
      </p>
    </div>
  </div>
</div>
<%= render "users/nav-icons", user: @user %>
<div class="posts container-fluid my-posts">
  <div class="row">
    <%= render "posts/index", posts: @posts %>
  </div>
  <%= paginate @posts %>
</div>