config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  resources :users, only: [:show, :index, :edit, :update] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'bookmarks' => 'bookmarks#index', as: 'bookmarks'
    get 'groups' => 'groups#index', as: 'groups'
    get 'notifications' => 'notifications#index', as: 'notifications'
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end
  resources :categories, except: [:destroy] do
    resources :category_images, only: [:create]
    resources :groups, except: [:show, :index, :update]
    get 'join' => 'categories#join'
    delete 'leave' => 'categories#leave'
  end
  resources :groups, only: [:show, :update] do
    resources :messages, only: [:create]
    get 'join' => 'groups#join'
    get 'allow/:id' => 'groups#allow', as: 'allow'
    delete 'leave/:id' => 'groups#leave', as: 'leave'
  end
  resources :tags
  get 'search' => 'searches#search'
  get 'tags/:tag_id/posts' => 'posts#search', as: 'tag_post'
  delete 'notifications/destroy_all' => 'notifications#destroy_all', as: 'notification'
  post 'follow/:id' => 'relationships#create', as: 'follow'
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow'
  post 'category_images/:category_image_id/favorite' => 'favorites#create', as: 'favorites'
  delete 'category_images/:category_image_id/favorite' => 'favorites#destroy', as: 'favorite'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_users, through: :bookmarks, source: :user
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  attachment :image

  validates :body, presence: true, length: { in: 2..300, allow_blank: true }

  # ブックマークされているか確かめる
  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  # タグが新しい場合を保存する
  def save_tag(sent_tags)
    current_tags = tags.pluck(:name) unless tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
    old_tags.each do |old|
      tags.delete Tag.find_by(name: old)
    end
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      tags << new_post_tag
    end
  end

  # コメントされた時にコメント通知を保存する
  def create_notification_comment!(current_user, comment_id)
    unless user_id == current_user.id
      save_notification_comment!(current_user, comment_id, user_id)
    end
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comments_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [:new, :create, :index, :search]
  before_action :ensure_current_user, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list = params[:post][:tag_name].split(nil)
    if @post.save
      @post.save_tag(tag_list)
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post_comments = @post.post_comments.all.order(created_at: :desc)
    @post_comment = PostComment.new
  end

  def index
    if params[:sort] == "popular"
      @posts = Post.left_joins(:bookmarks).group(:id).order("count(bookmarks.post_id) desc").page(params[:page]).per(12)
    else
      @posts = Post.order(created_at: :desc).page(params[:page]).per(12)
    end
  end

  def edit
    @tag_list = @post.tags.pluck(:name).join(" ")
  end

  def update
    tag_list = params[:post][:tag_name].split(nil)
    if @post.update(post_params)
      @post.save_tag(tag_list)
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def destroy
    Post.find_by(id: @post.id).destroy
    redirect_to posts_path
  end

  def search
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.posts.page(params[:page]).per(12)
  end

  private

  def post_params
    params.require(:post).permit(:body, :image)
  end

  def ensure_current_user
    post = Post.find(params[:id])
    unless post.user == current_user
      redirect_to posts_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= render "layouts/errors", obj: @post %>
<%= form_with model:post, local:true do |f| %>
  <div class="form-group">
    <%= f.text_area :body, rows: "15", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :タグ %>
    <%= f.text_field :tag_name, value:@tag_list, placeholder: "複数タグ付けする場合、半角スペースをあけてください", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :画像 %>
    <%= f.attachment_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <% if action_name == "new" %>
      <%= f.submit "投稿", class: "btn"  %>
    <% else %>
      <%= f.submit "更新", class: "btn"  %>
    <% end %>
  </div>
<% end %>

app/views/posts/_index.html.erb
<% posts.each do |post| %>
  <div class="col-lg-3 col-md-4 col-sm-5 d-flex justify-content-center">
    <div class="card mb-3" style="width: 15rem;">
      <%= link_to post_path(post) do %>
        <%= attachment_image_tag post, :image, fallback: "no-image.jpg",  class: "card-img-top" %>
      <% end %>
      <div class="card-body">
        <% if action_name != "top" %>
          <div class="bookmark-btn" id="bookmark-btn_<%= post.id %>">
            <%= render "bookmarks/bookmark-btn", post: post %>
          </div>
        <% end %>
        <div class="tags" id="text-hidden-1">
          <%= render "posts/tag", post: post %>
        </div>
        <p class="card-text", id="text-hidden-2">
          <%= post.body %>
        </p>
        <div class="user-text">
          <%= link_to user_path(post.user) do %>
            <%= attachment_image_tag post.user, :profile_image, fallback: "no-image.jpg", class: "profile-image-sm" %>
            <%= post.user.name %>
          <% end %>
          <small class="date"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></small>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_tag.html.erb
<% if post.tags.present? %>
  <% post.tags.each do |tag| %>
    <%= link_to tag_post_path(tag) do %>
    <i class="fas fa-tag"></i>
    <%= tag.name %>
    <% end %>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<div class="post container">
  <div class="col-md-8 offset-md-2">
    <%= render "posts/form", post: @post %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="posts container-fluid">
  <div class="new-post">
    <%= link_to new_post_path do %>
      <i class="fas fa-plus"></i>
    <% end %>
  </div>
  <div class="sub-field">
    <div class="sort-field">
      <%= link_to "新しい順", posts_path(sort: "newArrival") %>
      |
      <%= link_to "人気順", posts_path(sort: "popular") %>
    </div>
    <div class="search-field">
    　<%= form_tag search_path, method: :get do %>
    　　<%= text_field_tag (:word), '', placeholder: "post検索" %>
    　　<%= hidden_field_tag 'range', 'post' %>
    　　<%= button_tag type: 'submit', class: 'btn btn-default' do%>
          <i class="fas fa-search"></i>
    　　<% end %>
    　<% end %>
    </div>
  </div>
  <div class="row">
    <%= render "posts/index", posts: @posts %>
  </div>
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="post container">
  <div class="col-md-8 offset-md-2">
    <%= render "posts/form", post: @post %>
  </div>
</div>

app/views/posts/search.html.erb
<div class="posts container-fluid">
  <h5>"<%= @tag.name %>"検索結果</h5>
  <div class="row", style="margin: 0 auto;">
    <%= render "posts/index", posts: @posts %>
  </div>
  <%= paginate @posts %>
</div>

app/views/posts/show.html.erb
<div class="post container">
  <div class="row">
    <div class="post-field col-md-7">
      <div class="card">
        <%= attachment_image_tag @post, :image, fallback: "no-image.jpg", class: "card-img-top" %>
        <div class="card-body">
          <div id="bookmark-btn_<%= @post.id %>">
            <%= render "bookmarks/bookmark-btn", post: @post %>
          </div>
          <div class="tags">
            <%= render "posts/tag", post: @post %>
          </div>
          <p class="card-text">
            <%= simple_format @post.body %>
          </p>
          <div class="user-text">
            <%= link_to user_path(@post.user) do %>
              <%= attachment_image_tag @post.user, :profile_image, fallback: "no-image.jpg", class: "profile-image-sm" %>
              <%= @post.user.name %>
            <% end %>
            <small class="date"><%= @post.created_at.strftime("%Y-%m-%d %H:%M") %></small>
          </div>
        </div>
        <div class="post-setting">
          <% if @post.user_id == current_user.id %>
            <%= link_to "編集", edit_post_path(@post) %>
            <%= link_to "削除", post_path(@post), method: :delete, "data-confirm" => "本当に削除しますか？" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="comment-field col-md-4 offset-md-1">
      <div class="overflow-auto">
        <table class="table">
          <tbody id="post-comment_<%= @post.id%>" class="comments">
            <%= render "post_comments/comment", post_comments: @post_comments, post: @post %>
          </tbody>
        </table>
      </div>
      <%= render "layouts/errors", obj: @post_comment %>
      <%= form_with model:[@post, @post_comment], remote:true do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, rows: '3', placeholder: "コメントをここに", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "送信", class: "form-control" %>
        </div>
      <% end %>
    </div>
  </div>
</div>