config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  resources :users, only: [:show, :index, :edit, :update] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'bookmarks' => 'bookmarks#index', as: 'bookmarks'
    get 'groups' => 'groups#index', as: 'groups'
    get 'notifications' => 'notifications#index', as: 'notifications'
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end
  resources :categories, except: [:destroy] do
    resources :category_images, only: [:create]
    resources :groups, except: [:show, :index, :update]
    get 'join' => 'categories#join'
    delete 'leave' => 'categories#leave'
  end
  resources :groups, only: [:show, :update] do
    resources :messages, only: [:create]
    get 'join' => 'groups#join'
    get 'allow/:id' => 'groups#allow', as: 'allow'
    delete 'leave/:id' => 'groups#leave', as: 'leave'
  end
  resources :tags
  get 'search' => 'searches#search'
  get 'tags/:tag_id/posts' => 'posts#search', as: 'tag_post'
  delete 'notifications/destroy_all' => 'notifications#destroy_all', as: 'notification'
  post 'follow/:id' => 'relationships#create', as: 'follow'
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow'
  post 'category_images/:category_image_id/favorite' => 'favorites#create', as: 'favorites'
  delete 'category_images/:category_image_id/favorite' => 'favorites#destroy', as: 'favorite'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_users, dependent: :destroy
  has_many :users, through: :category_users
  has_many :category_images, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { in: 2..20, allow_blank: true }
  validates :introduction, presence: true, length: { in: 2..200, allow_blank: true }

  # カテゴリー登録されているか確かめる
  def category_user?(user)
    category_users.where(user_id: user.id).exists?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.users << current_user
    if @category.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def show
    @category_image = CategoryImage.new
    @groups = Group.includes(:group_users).where(category_id: @category.id).sort do |a, b|
      b.group_users.size <=> a.group_users.size
    end
    @category_images =
      CategoryImage.includes(:favorited_users).where(category_id: @category.id).sort do |a, b|
        b.favorited_users.size <=> a.favorited_users.size
      end
    @category_images = Kaminari.paginate_array(@category_images).page(params[:page]).per(15)
  end

  def index
    @categories = Category.includes(:category_users).sort do |a, b|
      b.category_users.size <=> a.category_users.size
    end
    @categories = Kaminari.paginate_array(@categories).page(params[:page]).per(12)
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  def join
    @category = Category.find(params[:category_id])
    unless @category.users.include?(current_user)
      @category.users << current_user
    end
  end

  def leave
    @category = Category.find(params[:category_id])
    @category.users.delete(current_user)
  end

  private

  def category_params
    params.require(:category).permit(:name, :introduction)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category-btn.html.erb
  <% if category.category_user?(current_user)%>
  　<%= link_to category_leave_path(category.id), method: :delete, remote:true do %>
      <i class="fas fa-check"></i>
  　<% end %>
  <% else %>
    <%= link_to category_join_path(category.id), remote:true do %>
    　<i class="fas fa-user-plus"></i>
    <% end %>
  <% end %>

app/views/categories/_index.html.erb
<% categories.each do |category| %>
  <tr>
    <td onclick='window.location="<%= '../categories/' + category.id.to_s %>"' role="link" class="pointer">
      <p class="category-text">
        <span><%= category.name %></span>
        <%= category.introduction %>
      </p>
    </td>
    <% if action_name != "top" %>
      <td id="category-btn_<%= category.id %>" class="category-btn">
        <%= render "categories/category-btn", category: category %>
      </td>
    <% end %>
  </tr>
<% end %>

app/views/categories/edit.html.erb
<div class="category container">
  <div class="col-md-8 offset-md-2">
    <%= render "layouts/errors", obj: @category %>
    <%= form_with model:@category, local:true do |f| %>
      <div class="form-group">
        <%= f.label :紹介 %>
        <%= f.text_area :introduction, rows: "15", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "更新", class: "form-control btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="categories container-fluid">
  <div class="new-category">
    <%= link_to new_category_path do %>
      <i class="fas fa-plus"></i>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-6 offset-md-1">
      <table class="table">
        <tbody>
          <%= render "categories/index", categories: @categories %>
        </tbody>
      </table>
      <%= paginate @categories %>
    </div>
    <div class="col-md-5">
      <div class="search-field">
        <% if user_signed_in? %>
        　<%= form_tag search_path, method: :get do %>
        　　<%= text_field_tag (:word), '', placeholder: "category検索" %>
        　　<%= hidden_field_tag 'range', 'category' %>
        　　　<%= button_tag type: 'submit', class: 'btn btn-default' do %>
              <i class="fas fa-search"></i>
        　　<% end %>
        　<% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/join.js.erb
$("#category-btn_<%= @category.id %>").html("<%= j(render 'categories/category-btn', category: @category) %>")

app/views/categories/leave.js.erb
$("#category-btn_<%= @category.id %>").html("<%= j(render 'categories/category-btn', category: @category) %>")

app/views/categories/new.html.erb
<div class="category container">
  <div class="col-md-8 offset-md-2">
    <%= render "layouts/errors", obj: @category %>
    <%= form_with model:@category, local:true do |f| %>
      <div class="form-group">
        <%= f.label :カテゴリー名 %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :紹介 %>
        <%= f.text_area :introduction, rows: "15", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "作成", class: "form-control btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="category container">
  <div class="row">
    <div class="col-md-6">
      <h3><%= @category.name %></h3>
      <div id="category-btn_<%= @category.id %>" class="category-btn">
        <%= render "categories/category-btn", category: @category %>
      </div>
      <div class="ctegory-setting">
        <% if @category.category_user?(current_user)%>
          <%= link_to edit_category_path(@category.id) do %>
            <i class="far fa-edit"></i>
          <% end %>
        <% end %>
      </div>
      <div class="card">
        <%= simple_format @category.introduction %>
      </div>
    </div>
    <div class="group-field col-md-6">
      <p>グループ一覧</p>
      <% if @category.category_user?(current_user)%>
        <%= link_to new_category_group_path(@category.id) do %>
          <i class="fas fa-plus"></i>
        <% end %>
      <% end %>
      <div class="overflow-auto">
        <table class="table">
          <tbody>
            <%= render "groups/index", groups: @groups %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="images-field">
    <div id="category-images" class="category-images">
      <%= render "category_images/images", category_images: @category_images %>
    </div>
    <% if @category.category_user?(current_user)%>
      <%= form_with model:[@category, @category_image], local:true do |f| %>
        <div class="form-group">
          <%= f.attachment_field :image, class: "form-control" %>
          <%= f.submit "追加", class: "form-control" %>
        </div>
      <% end %>
    <% end %>
    <%= paginate @category_images %>
  </div>
</div>